[2023-12-26T01:09:09.964+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract-transform-load.load manual__2023-12-26T01:04:08.423568+00:00 [queued]>
[2023-12-26T01:09:09.969+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract-transform-load.load manual__2023-12-26T01:04:08.423568+00:00 [queued]>
[2023-12-26T01:09:09.969+0000] {taskinstance.py:2171} INFO - Starting attempt 2 of 6
[2023-12-26T01:09:09.975+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2023-12-26 01:04:08.423568+00:00
[2023-12-26T01:09:09.979+0000] {standard_task_runner.py:60} INFO - Started process 173 to run task
[2023-12-26T01:09:09.982+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract-transform-load', 'load', 'manual__2023-12-26T01:04:08.423568+00:00', '--job-id', '144', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmpqgex2aiv']
[2023-12-26T01:09:09.984+0000] {standard_task_runner.py:88} INFO - Job 144: Subtask load
[2023-12-26T01:09:10.018+0000] {task_command.py:423} INFO - Running <TaskInstance: extract-transform-load.load manual__2023-12-26T01:04:08.423568+00:00 [running]> on host 023f8da17198
[2023-12-26T01:09:10.064+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='william' AIRFLOW_CTX_DAG_ID='extract-transform-load' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T01:04:08.423568+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T01:04:08.423568+00:00'
[2023-12-26T01:09:10.088+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api.py", line 58, in load
    cursor.copy_from(f, 'sales', sep=';', )
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "actual_price"
CONTEXT:  COPY sales, line 1, column actual_price: "actual_price"

[2023-12-26T01:09:10.232+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=extract-transform-load, task_id=load, execution_date=20231226T010408, start_date=20231226T010909, end_date=20231226T010910
[2023-12-26T01:09:10.239+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 144 for task load (invalid input syntax for type numeric: "actual_price"
CONTEXT:  COPY sales, line 1, column actual_price: "actual_price"
; 173)
[2023-12-26T01:09:10.283+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T01:09:10.295+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
