[2023-12-26T01:09:18.971+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract-transform-load.load manual__2023-12-26T01:09:18.215745+00:00 [queued]>
[2023-12-26T01:09:18.975+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract-transform-load.load manual__2023-12-26T01:09:18.215745+00:00 [queued]>
[2023-12-26T01:09:18.976+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-26T01:09:18.981+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2023-12-26 01:09:18.215745+00:00
[2023-12-26T01:09:18.986+0000] {standard_task_runner.py:60} INFO - Started process 177 to run task
[2023-12-26T01:09:18.990+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract-transform-load', 'load', 'manual__2023-12-26T01:09:18.215745+00:00', '--job-id', '146', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmp31r_xpt7']
[2023-12-26T01:09:18.992+0000] {standard_task_runner.py:88} INFO - Job 146: Subtask load
[2023-12-26T01:09:19.032+0000] {task_command.py:423} INFO - Running <TaskInstance: extract-transform-load.load manual__2023-12-26T01:09:18.215745+00:00 [running]> on host 023f8da17198
[2023-12-26T01:09:19.251+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='william' AIRFLOW_CTX_DAG_ID='extract-transform-load' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T01:09:18.215745+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T01:09:18.215745+00:00'
[2023-12-26T01:09:19.289+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api.py", line 58, in load
    cursor.copy_from(f, 'sales', sep=';', )
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type numeric: "actual_price"
CONTEXT:  COPY sales, line 1, column actual_price: "actual_price"

[2023-12-26T01:09:19.296+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=extract-transform-load, task_id=load, execution_date=20231226T010918, start_date=20231226T010918, end_date=20231226T010919
[2023-12-26T01:09:19.301+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 146 for task load (invalid input syntax for type numeric: "actual_price"
CONTEXT:  COPY sales, line 1, column actual_price: "actual_price"
; 177)
[2023-12-26T01:09:19.324+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T01:09:19.335+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
