[2023-12-26T01:10:50.803+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: extract-transform-load.load manual__2023-12-26T01:10:49.620031+00:00 [queued]>
[2023-12-26T01:10:50.808+0000] {taskinstance.py:1957} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: extract-transform-load.load manual__2023-12-26T01:10:49.620031+00:00 [queued]>
[2023-12-26T01:10:50.809+0000] {taskinstance.py:2171} INFO - Starting attempt 1 of 6
[2023-12-26T01:10:50.815+0000] {taskinstance.py:2192} INFO - Executing <Task(_PythonDecoratedOperator): load> on 2023-12-26 01:10:49.620031+00:00
[2023-12-26T01:10:50.819+0000] {standard_task_runner.py:60} INFO - Started process 206 to run task
[2023-12-26T01:10:50.823+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'extract-transform-load', 'load', 'manual__2023-12-26T01:10:49.620031+00:00', '--job-id', '149', '--raw', '--subdir', 'DAGS_FOLDER/api.py', '--cfg-path', '/tmp/tmp3d_t89yb']
[2023-12-26T01:10:50.824+0000] {standard_task_runner.py:88} INFO - Job 149: Subtask load
[2023-12-26T01:10:50.863+0000] {task_command.py:423} INFO - Running <TaskInstance: extract-transform-load.load manual__2023-12-26T01:10:49.620031+00:00 [running]> on host 023f8da17198
[2023-12-26T01:10:51.101+0000] {taskinstance.py:2481} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='william' AIRFLOW_CTX_DAG_ID='extract-transform-load' AIRFLOW_CTX_TASK_ID='load' AIRFLOW_CTX_EXECUTION_DATE='2023-12-26T01:10:49.620031+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-12-26T01:10:49.620031+00:00'
[2023-12-26T01:10:51.122+0000] {taskinstance.py:2699} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/decorators/base.py", line 242, in execute
    return_value = super().execute(context)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/api.py", line 58, in load
    cursor.copy_from(f, 'sales', sep=';', )
psycopg2.errors.InvalidTextRepresentation: invalid input syntax for type double precision: "actual_price"
CONTEXT:  COPY sales, line 1, column actual_price: "actual_price"

[2023-12-26T01:10:51.131+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=extract-transform-load, task_id=load, execution_date=20231226T011049, start_date=20231226T011050, end_date=20231226T011051
[2023-12-26T01:10:51.136+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 149 for task load (invalid input syntax for type double precision: "actual_price"
CONTEXT:  COPY sales, line 1, column actual_price: "actual_price"
; 206)
[2023-12-26T01:10:51.161+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2023-12-26T01:10:51.174+0000] {taskinstance.py:3281} INFO - 0 downstream tasks scheduled from follow-on schedule check
